# Site settings
title: MET DATA QA/QC
email: fox@tinybike.net
description: > # this means to ignore newlines until "baseurl:"
    This is the main site for the MET QA/QC between Oregon State University and the FSL for the H.J. Andrews Forest
baseurl: /metQC # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: a_fox_box
github_username:  dataronin
pygments: true

# Build settings
#markdown: kramdown
#markdown: maruku
markdown: kramdown

# Make redcarpet behave like GitHub Flavored Markdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]